### ISSUE TITLE
`advance_time` waits forever if no timers are registered

### ISSUE THREAD

**Issue by extremeandy** [communityvi/async-time-mock#15]
```rust
let (clock, registry) = MockableClock::mock();

registry
    .advance_time(std::time::Duration::from_secs(1))
    .await;
```

The above call to `advance_time` will never return because of this:

```rust
// If no timer has been scheduled yet, wait for one to be scheduled
self.any_timer_scheduled_signal.listen().await;
```

Seems like a different mechanism might be needed to allow this call to proceed if no timers are registered.

**Comment by FSMaxB** [comment]
Waiting for a timer is quite essential to prevent a race between the code you're testing and the test itself. Without it, the time would just be advanced immediately, before the tested code even had any chance of starting it's timer (It has about a 100% chance of failing if you start the tested code via `tokio::spawn`, because the spawning takes more time than the `advance_time` right afterwards).

 But I see how this becomes an issue if the tested code isn't behaving correctly and not actually scheduling a timer. At that point, your tests just wait forever.

Maybe this needs some kind of "real" time timeout after which `advance_time` gives up waiting? I would argue though, that it should not actually advance the mock time after the timeout expires but just fail with an error.

**Comment by extremeandy** [comment]
Yeah agreed a mechanism is needed so that the registry knows when all timer calls have been registered and it can advanced. However, equally there might be _multiple_ timer registrations, and the current implementation will advance on the first one, and miss subsequent ones.

I discovered after posting here that `tokio` already has support for pause/resume/advance of time, via the `test-util` feature. This solves the above issue by allowing the clock to be controlled by the futures runtime itself -- meaning all futures can be polled until `Pending` before advancing the clock. This means any race condition like you describe can be avoided. I don't really see any other way to avoid this cleanly without having the async runtime handle it.

This also means code can just use `tokio::time::sleep` statically without needing anything to be passed in as an argument.

The `tokio` way also nicely handles advancing the clock for you, based on whatever `sleep` calls were made to it prior to polling.

Here's an example of how to use it with streams. Streams are particularly hard to work with when there is a "guard" (`TimeHandlerGuard`) as that guard must be propagated with the stream values, which makes for a lot of boilerplate.

```rust
#[tokio::test(flavor = "current_thread", start_paused = true)]
async fn test() {
    // Step #1: Set up your input stream. Perhaps you want to simulate emissions over
    // time by controlling the time at which each value is emitted.
    let input = timed_stream([
        (1, Duration::from_millis(0)),
        (2, Duration::from_millis(1500)),
        (3, Duration::from_millis(2000)),
    ]);

    // Step #2: Do some work that you want to test. In this case I am delaying
    // each value by 500ms and multiplying by 2.
    let output = input.flat_map(|value| {
        let delayed = async move {
            tokio::time::sleep(Duration::from_millis(500)).await;
            value * 2
        };
        stream::once(delayed)
    });

    // Step #3: Timestamp the results
    let actual_results = timestamp_stream(output).collect::<Vec<_>>().await;

    // Step #4: Detail expected results - values and timings.
    let expected_results = vec![
        (1 * 2, Duration::from_millis(0 + 500)),
        (2 * 2, Duration::from_millis(1500 + 500)),
        (3 * 2, Duration::from_millis(2000 + 500)),
    ];

    // Step #5: Assert!
    assert_eq!(expected_results, actual_results);
}

fn timed_stream<T>(items: impl IntoIterator<Item = (T, Duration)>) -> impl Stream<Item = T> {
    let initial_time = tokio::time::Instant::now();
    stream::iter(items).flat_map(move |(value, duration)| {
        let delayed = async move {
            tokio::time::sleep_until(initial_time + duration).await;
            value
        };

        stream::once(delayed)
    })
}

pub fn timestamp_stream<T>(
    stream: impl Stream<Item = T>,
) -> impl Stream<Item = (T, tokio::time::Duration)> {
    let now = tokio::time::Instant::now();
    stream.map(move |item| (item, tokio::time::Instant::now() - now))
}
```

**Comment by extremeandy** [comment]
> Maybe this needs some kind of "real" time timeout after which `advance_time` gives up waiting? I would argue though, that it should not actually advance the mock time after the timeout expires but just fail with an error.

I think having to do something like this might introduce some non-deterministic behaviour or race conditions that might impact reliability of tests :/

**Comment by FSMaxB** [comment]
> I discovered after posting here that tokio already has support for pause/resume/advance of time, via the test-util feature.

Yes, I'm aware of this feature, but have had issues with it in the past because it was auto-advancing the time under certain circumstances without ever advancing it in the test code. My understanding of that issue was quite vague though, so I might have completely misinterpreted what was going on.

> This solves the above issue by allowing the clock to be controlled by the futures runtime itself -- meaning all futures can be polled until Pending before advancing the clock. 

Is that what it's doing, waiting until every futures on the runtime have been polled until pending? If so, that is very cool. It would be great to incorporate that in `async-time-mock` somehow, although not sure how that would even be possible to be honest.

> This also means code can just use tokio::time::sleep statically without needing anything to be passed in as an argument.

Passing in the `TimerRegistry` explicitly was an explicit decision I made. I want things to work at all first, only then try to make it more ergonomic to use. The blog post this is based on uses a thread-local to achieve this if I'm not mistaken. And I think tokio at least also has some kind of task-local concept or concept of state that is global to a given runtime. It should be possible to put a timer registry in one of those shared contexts in order to not have to pass it in explicitly. Although I'm still not 100% sure if that kind of implicit behavior is actually desirable.

> Streams are particularly hard to work with when there is a "guard" (TimeHandlerGuard) as that guard must be propagated with the stream values, which makes for a lot of boilerplate.

The purpose of the `TimeHandlerGuard` is to tell the `TimerRegistry` once all side-effects of whatever operation the timer triggered have finished. This is important for asserting the effects of an expired timer in tests, because otherwise you get into a race between the assertion in your test, right after you advanced the test time, and the tested code that performs some observable change that can be asserted.

If you don't care about the side-effects of a particular operation, it's totally fine to drop the `TimeHandlerGuard` immediately.

The `TimeHandlerGuard` is basically **the** main feature this library provides over just using the tokio test helpers.

> > Maybe this needs some kind of "real" time timeout after which advance_time gives up waiting? I would argue though, that it should not actually advance the mock time after the timeout expires but just fail with an error.
> 
> I think having to do something like this might introduce some non-deterministic behaviour or race conditions that might impact reliability of tests :/

I would see that as a separate explicit parameter. Either to `advance_time` or when constructing the `TimerRegistry`. By default there would either be no timeout, or it would be something quite large (e.g. 1 minute). The main purpose of that would be having a fallback so if you have a broken test or tested code, it eventually fails instead of potentially blocking a CI run for hours or even indefinitely.

**Comment by FSMaxB** [comment]
Looking into this further, I don't think implementing a timeout in `advance_time` is feasible because timeouts are runtime specific so they can't actually be done in `async-time-mock-core`.

What would work is to implement timeouts as extension trait in e.g. `async-time-mock-tokio` etc. I will hold off on implementing something like that for now, unless many people actually ask for it.

Closing this for now because the original question was answered.
